# source("R/packages.R")
library(targets)
library(dplyr)
library(stringr)
library(readr)
library(here)
# library(sf)
# library(tmap)
# source("R/read-data.R")
# source("R/clean-data.R")
# source("R/process-data.R")
# source("Y:/fcoloma/package_fabi/R/basics_analisis.R")
library(stringr)
library(purrr)
# library(haven)
# library(tidyverse)
library(lubridate)
library(arrow)
library(tarchetypes)
# library(ca)
# library(pscl)
# library(anthro)
library(haven)
library(caret)

library("sf")
library("readxl")

# library(FactoMineR)
# library(factoextra)
# library(ggbiplot)
library(ggplot2)


library(glmmTMB)

# library(glmmPen)

